title : Elden Ring - Samuel SÃ¡ez
description: 'Elden Ring'

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: "/Wall-E"
url: "https://kamplen3.github.io" 
plugins: [jekyll-gist]
permalink: /:year/:month/:title.html
