title : Elden Ring - Samuel SÃ¡ez
description: 'Elden Ring'

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: kamplen3.github.io/Wall-E
plugins: [jekyll-gist]
permalink: /:year/:month/:title.html
