title : Wall-E - Samuel SÃ¡ez
description: 'A Modern Jekyll Theme'

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
plugins: [jekyll-gist]
permalink: /:year/:month/:title.html
